baseURL = "https://demos.julien-maury.dev/hugo-theme-ava/"
languageCode = "en"
title = "Hugo Ava Theme"
theme = "hugo-themes-ava"
paginate = 7
mainSections = "post"

[languages]
  [languages.en]
      languageName = "English"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[params]
  ga_id=""
  mainSections = ["post"]


  [params.meta_tags]
    meta_description = "Ava is a light theme for your blog with essential features you might dig in."
    meta_og_title = "Art Attack"
    meta_og_sitename = "Art Attack"
    meta_og_type = "website"
    meta_og_url = "https://hugo-ava.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/jmau111/hugo-theme-ava/main/images/default.jpeg"
    meta_og_description = "Learn about how we made a kinnetic sculpture"
    meta_twitter_card = "summary"
    meta_twitter_site = "@gohugoio"
    meta_twitter_creator = "@gohugoio"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false
        pygmentsUseClasses = true
        pygmentsCodefences = true

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
    name = "Process"
    url = "/process/"
    weight = 2

[[menu.main]]
    name = "System"
    url = "/system/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
